version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
